---
title: "just sorting out the matrix and coldata cleanup"
author: "Dan Griffiths"
date: "2023-11-28"
output:
  html_document: default
---

### Load libraries

```{r libraries, message = FALSE}
library(limma)
library(Glimma)
library(tidyverse)
library(DESeq2)
library(org.Hs.eg.db)
library(pheatmap)
library(EnhancedVolcano)
library(ComplexHeatmap)
library(gplots)
library(msigdbr)
```


### Import raw counts, coldata
```{r}
load("../workset_workspace_01/subread/FeatCounts_Rsub.RData")
counts <- as.matrix(counts$counts)
# Find column indices that don't contain 'markdup' in the names
selected_columns <- grep("markdup", colnames(counts), invert = TRUE)
# Select the columns based on the indices
filtered_matrix <- counts[, selected_columns]
# Remove ".sorted.bam" from column names
new_colnames <- sub("\\.sorted\\.bam", "", colnames(filtered_matrix))
# Assign the modified column names back to the matrix
colnames(filtered_matrix) <- new_colnames
counts <- filtered_matrix
```


```{r, message=FALSE}
coldata <- readr::read_csv('../workset_workspace_01/source_data/coldata.csv') %>% as.data.frame()
identical(colnames(counts), coldata$sample)
```


### Generate DESeq2 object
IL7 removed from analysis completely.
```{r, message=FALSE, warning=FALSE}
dds <- DESeqDataSetFromMatrix(counts,coldata, design = ~healthy_donor + condition)
dds <- dds[ , !dds$condition %in% c("IL7") ] 
dds$condition <- droplevels(dds$condition)


newcounts <- counts(dds)
newcounts <- as.matrix(newcounts)
newcoldata <- as.data.frame(colData(dds))

write_rds(newcounts, "counts_matrix_raw.rds")
write_rds(newcoldata, "coldata_dataframe.rds")
```
