---
title: "Heatmap IL2 vs IL21"
author: "Dan Griffiths"
date: "2023-11-14"
output:
  html_document: default
  pdf_document: default
---

### Load libraries

```{r libraries, message = FALSE}
library(limma)
library(Glimma)
library(edgeR)
library(tidyverse)
library(DESeq2)
library(org.Hs.eg.db)
library(pheatmap)
library(EnhancedVolcano)
library(ComplexHeatmap)
library(gplots)
library(vsn)
```

```{r}
set.seed(42) # set seed for reproducibility in clustering
```

### Import raw counts, coldata

```{r, message=FALSE, echo=FALSE}
ensembl.counts <- readr::read_rds('source_data/DDS_Full_counts.RDS') %>% counts(.) %>% as.matrix()
coldata <- readr::read_csv('./source_data/coldata.csv') %>% as.data.frame()
identical(colnames(ensembl.counts), coldata$sample)
```

### Prepare and filter counts

```{r}
counts <- ensembl.counts
# Convert counts matrix to a data frame
df <- as.data.frame(counts) %>% rownames_to_column(var = "ensembl.id")

# Add SYMBOL and GENETYPE columns using AnnotationDbi's mapIds
df <- df %>%
  dplyr::mutate(
    SYMBOL = mapIds(org.Hs.eg.db, keys = ensembl.id, column = "SYMBOL", keytype = "ENSEMBL"),
    GENETYPE = mapIds(org.Hs.eg.db, keys = ensembl.id, column = "GENETYPE", keytype = "ENSEMBL")
  )

# Filter out rows where SYMBOL is NA
df_filtered <- df[complete.cases(df$SYMBOL),]
# Count the number of differences between df$SYMBOL and df_filtered$SYMBOL
symbol_diff_count <- sum(!(df$SYMBOL %in% df_filtered$SYMBOL))

# QC summary
qc_summary <- data.frame(
  symbol_has_name = symbol_diff_count,
  All_SYMBOL = length(df_filtered$SYMBOL),
  dup_SYMBOL = sum(duplicated(df_filtered$SYMBOL, na.rm = TRUE)),
  protein_coding = sum(df_filtered$GENETYPE == "protein-coding", na.rm = TRUE)
)

# Display QC summary
DT::datatable(as.data.frame(table(df$GENETYPE, useNA = "ifany")))
DT::datatable(t(qc_summary))

# Filter conditions
filter_conditions <- df %>%
  dplyr::filter(
    !is.na(SYMBOL),           # Remove rows with NA in SYMBOL
    !duplicated(SYMBOL),      # Remove rows with duplicated SYMBOL
    GENETYPE == "protein-coding"
  )

# Apply filters to counts matrix
counts <- counts[row.names(counts) %in% filter_conditions$ensembl.id, ]

# Now, you can change Ensembl IDs to their associated SYMBOL IDs
# Assuming the filtered counts matrix has Ensembl IDs as row names
row_names <- row.names(counts)
symbol_ids <- filter_conditions$SYMBOL[match(row_names, filter_conditions$ensembl.id)]

# Update row names with SYMBOL IDs
row.names(counts) <- symbol_ids
```

### Generate DESeq2 object

```{r}
dds <- DESeqDataSetFromMatrix(counts,coldata, design =~healthy_donor + condition)
dds <- dds[ , !dds$condition %in% c("IL7") ] # can remove conditions if required
dds$condition <- droplevels(dds$condition)
smallestGroupSize <- 3
keep <- rowSums(counts(dds) >= 10) >= smallestGroupSize
dds <- dds[keep,]
dds <- DESeq(dds)
resultsNames(dds)
vst <- varianceStabilizingTransformation(dds)
vsn::meanSdPlot(assay(vst))
```


### All variance, all conditions, heatmap plot

```{r, fig.height=10,fig.width=10}
topVarGenes <- order(rowVars(assay(vst)), decreasing = TRUE)
mat  <- assay(vst)[ topVarGenes[1:30], ]
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(dds))
column_ha = HeatmapAnnotation(Healthy_Donor = anno$healthy_donor, Condition = anno$condition)
Heatmap(mat,name = "mat",
        column_title = "All variance, all conditions", 
        top_annotation = column_ha, 
        cluster_columns = FALSE, 
        cluster_rows = TRUE , 
        column_split = anno$healthy_donor
        )
```

### DESeq2 results pairwise each condition

```{r}
res.il15 <- results(dds,contrast = c("condition","IL21","IL15"))
res.sig.il15 <- subset(res.il15, padj < 0.1)
lfc.il15 <- res.sig.il15[ order(res.sig.il15$log2FoldChange, decreasing=TRUE), ]
lfc.il15
res.il2 <- results(dds,contrast = c("condition","IL21","IL2"))
res.sig.il2 <- subset(res.il2, padj < 0.1)
lfc.il2 <- res.sig.il2[ order(res.sig.il2$log2FoldChange, decreasing=TRUE), ]
lfc.il2
# res.ust <- results(dds,contrast = c("condition","IL21","UST"))
# res.sig.ust <- subset(res.ust, padj < 0.1)
# lfc.ust <- res.sig.ust[ order(res.sig.ust$log2FoldChange, decreasing=TRUE), ]
# lfc.ust
```

### Venn diagram common genes 

```{r}
## Data preparation
il15.degs <- row.names(lfc.il15)
il2.degs <- row.names(lfc.il2)
# ust.degs <- row.names(lfc.ust)
list.degs <- paste(c(il15.degs,il2.degs))
list.degs <- unique(list.degs)
print(paste0(c("length of all unique genes found in all conditions: ",length(list.degs)),collapse = ""))

# Create a Venn-diagram given just the list of gene-names for both sets
venn(list("IL15vsIL21" = il15.degs,
          "IL2vsIL21" = il2.degs
          ), )

common_genes <- Reduce(intersect, list(il2.degs, il15.degs))
print(paste0(c("length of common genes: ",length(common_genes)),collapse = ""))

df_common <- subset(lfc.il2, rownames(lfc.il2) %in% common_genes)
df_common
```


```{r,fig.height=10,fig.width=10}
group_indices <- which(colData(dds)$your_column_name == "IL21")
vst_data <- assay(vst)[, group_indices]
topVarGenes <- order(rowVars(vst_data), decreasing = TRUE)
mat  <- assay(vst)[common_genes[1:20], ]
mat  <- mat - rowMeans(mat)
anno <- as.data.frame(colData(dds))
column_ha = HeatmapAnnotation(Healthy_Donor = anno$healthy_donor, 
                              Condition = anno$condition
                              )

Heatmap(mat, 
        name = "Relative variance",
        column_title = "Common genes differentially expressed in IL21 vs IL15, and IL21 vs IL2; variance stablised expression heatmap", 
        top_annotation = column_ha, 
        cluster_columns = FALSE, 
        column_split = anno$healthy_donor,
        cluster_rows = TRUE
        )
```




## R session info

```{r}
sessionInfo()
```
